#!/usr/bin/env python3
"""Embed api/public assets into a Python module for Vercel serverless bundles."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "api" / "public"
OUT = ROOT / "api" / "_bundled_assets.py"

MEDIA_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
}


def main() -> None:
    if not PUBLIC.is_dir():
        raise SystemExit(f"Missing static directory: {PUBLIC}")

    assets: dict[str, str] = {}
    media_types: dict[str, str] = {}
    for path in sorted(PUBLIC.iterdir()):
        if not path.is_file():
            continue
        assets[path.name] = path.read_text(encoding="utf-8")
        media_types[path.name] = MEDIA_TYPES.get(path.suffix, "text/plain; charset=utf-8")

    OUT.write_text(
        "# Auto-generated by scripts/bundle_static.py — do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        f"ASSETS: dict[str, str] = {json.dumps(assets, ensure_ascii=False)}\n\n"
        f"MEDIA_TYPES: dict[str, str] = {json.dumps(media_types, ensure_ascii=False)}\n",
        encoding="utf-8",
    )
    print(f"Bundled {len(assets)} files into {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
